// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
  docs: [
	  {
		  type: "doc",
		  label: "Introduction",
		  id: "introduction"
	  },
	  {
      type: "category",
      label: "Installation & Setup",
      collapsible: true,
      collapsed: false,
      items: [
	      "installation-and-setup/installation",
	      "installation-and-setup/setup",
	    ]
	  },
	  {
		  type: "category",
		  label: "CLI",
		  collapsible: true,
		  collapsed: false,
		  items: [
			  "cli/app-mobame-download",
			  "cli/app-blog-download",
		  ]
	  },
	  {
		  type: "category",
		  label: "API",
		  collapsible: true,
		  collapsed: false,
		  items: [
			  "api/apps-lists",
			  "api/request-endpoint",
			  "api/request-attribute",
			  "api/asset-pre-download",
		  ]
	  }
	]
};

export default sidebars;
